### ISSUE TITLE
Weekly for 2016/01/22

### ISSUE THREAD

**Issue by swaylq** [dyweb/iOS-stuff#1]
- [x] @swaylq 
- [x] @xplorld

**Comment by at15** [comment]
0.0 sway holy high

**Comment by swaylq** [comment]
iOS安全

获取出厂UUID的代码

```
NSString *getIMEI()
{
    void *connection = _CTServerConnectionCreate(kCFAllocatorDefault, NULL, NULL);

    NSDictionary *info = nil;
    struct CTResult result;
    _CTServerConnectionCopyMobileIdentity(&result, connection, &info);
    [info autorelease];
    CFRelease(connection);

    NSString* IMEI = (NSString*)info[(NSString*)kCTMobileEquipmentInfoIMEI];
    return IMEI;
}
```

**Comment by arrowrowe** [comment]
Sway holy high!

**Comment by arrowrowe** [comment]
更新: 暂不建立 iOS 组邮件列表.

---

~~iOS 组没有邮件列表.~~
- [ ] ~~烦请组长 @xplorld 或副组长 @swaylq 提供, 形如 `RealName1 <mailname1@gmail.com>, RealName2 <mailname2@gmail.com>, ...` 的列表. 包括全体成员一份, 核心成员一份.~~
- [ ] ~~命名 iOS 组成员邮件列表名. 默认 `ios-members@dongyue.io`.~~
- [ ] ~~命名 iOS 组核心邮件列表名, 默认 `ios@dongyue.io`.~~

~~周报邮件发送方式与 Web 组方式一致, 若有疑问请询 Web 周报组任何一名成员. 建议统一使用 `weekly@dongyue.io` 作为发件人, 如有其他需求联系我.~~

**Comment by swaylq** [comment]
@arrowrowe 鉴于iOS人数较少，并不准备发周报，只是把技术知识积累一下，以后人多了再发周报

**Comment by at15** [comment]
@swaylq 嗯，我觉得可行，反正就那么几个人，还都是男的，安卓组现在也都是男的了....东岳要变交大最大的同性交友社区了.... 为什么感觉这件事我功不可没(~~在责难逃~~) 

@arrowrowe 水果组估计全体现任成员就都是核心成员了......

**Comment by xplorld** [comment]
@at15 目前已知成员3人……

**Comment by swaylq** [comment]
- [浏览大图的一种实现方式](http://www.cnblogs.com/CyanStone/p/5153564.html)

**Comment by swaylq** [comment]
- [Tweak 简单教程](http://blog.csdn.net/justinjing0612/article/details/9745557)

**Comment by at15** [comment]
@xplorld what's the name of the swap image effect library you showed us today in wechat, you can post them in this issue.

**Comment by xplorld** [comment]
https://github.com/fdzsergio/SFFocusViewLayout
