### ISSUE TITLE
Migrate into web weekly?

### ISSUE THREAD

**Issue by ComMouse** [dyweb/iOS-stuff#3]
Since this weekly is not maintained anymore, would it be better to merge it into web weekly?

@xplorld

**Comment by at15** [comment]
👍

**Comment by xplorld** [comment]
QAQ
Sincerely apologize for the ignorance on this weekly.
Maybe we can watch for one or two more months, I would try to maintain it.
See if I can do that

**Comment by ComMouse** [comment]
OK
